### ISSUE TITLE
NameError: global name 'ConnectionRefusedError' is not defined

### ISSUE THREAD

**Issue by mjnovice** [unixsurfer/haproxyadmin#2]
https://github.com/unixsurfer/haproxyadmin/blob/master/haproxyadmin/internal.py line 89.

**Comment by unixsurfer** [comment]
Are you running python 2 or python 3?

**Comment by mjnovice** [comment]
I am running python 2.

**Comment by mjnovice** [comment]
@unixsurfer

**Comment by mjnovice** [comment]
@unixsurfer any updates ?

**Comment by unixsurfer** [comment]
@mjnovice I've just pushed a patch for this. Please test it.
FYI: 0.4.0 release will drop support for Python 2

**Comment by jraby** [comment]
@unixsurfer  FYI, there are 2 other instances of `Connection*Error`  in `haproxyadmin/utils.py`.

It still throws when creating a HAProxy object on py2:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from haproxyadmin import haproxy
>>> hap = haproxy.HAProxy(socket_dir='/var/run/haproxy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "haproxyadmin/haproxy.py", line 110, in __init__
    if is_unix_socket(_file) and connected_socket(_file):
  File "haproxyadmin/utils.py", line 179, in connected_socket
    except (ConnectionRefusedError, PermissionError, socket.timeout, OSError):
NameError: global name 'ConnectionRefusedError' is not defined
```

Not sure how to fix this, should it catch only OSError and not its subclasses (`Connection*Error` and `PermissionError`) ?
